run: run1 run2 run3 run4 run5

run1:
	racket "./SchemeFlipped1.rkt"

run2:
	racket "./SchemeFlipped2.rkt"

run3:
	racket "./SchemeFlipped3.rkt"

run4:
	racket "./SchemeFlipped4.rkt"

run5:
	racket "./SchemeFlipped5.rkt"

clean:
	rm -f *.bak